New version of mysql-backup

diff --git a/mysql-backup b/mysql-backup
--- a/mysql-backup
+++ b/mysql-backup
@@ -1,9 +1,6 @@
 #!/bin/bash
 #===============================================================================
 # mysql-backup :
-# Date    :  2016/09/18 Start
-# Copyright: Original code by Yusuke Komori.
-#                       Copyright (c) 2016. Yusuke Komori, All rights reserved.
 #===============================================================================
 
 SCRIPT_BASE=`echo $(cd $(dirname $0); pwd)`
@@ -23,9 +20,12 @@ DATE_FORMAT=+%Y%m%d
 DUMP_OPT=(--lock-all-tables --hex-blob --add-drop-database --add-drop-table)
 DUMP_OPT_INFORMATION_SCHEMA=""
 DUMP_OPT_MYSQL=(--lock-all-tables --events)
-TAR_OPT=c
+TAR_OPT=(-c)
 
-_SYSLOG=
+cat /proc/$$/cgroup | egrep -q '^[0-9]+:name=systemd:/system.slice'
+[[ $? -eq 0 ]] && SYSTEMD_SLICE=yes
+
+[[ "${SYSTEMD_SLICE}" != 'yes' ]] && __MSG_COL=70
 
 #-------------------------------------------------------------------------------
 #- common functions ------------------------------------------------------------
@@ -35,7 +35,7 @@ __setup_color() { #{{{
   local COLOR_MAP=(\
     BLACK 0 MAROON 1 GREEN 2 OLIVE 3 NAVY 4 PURPLE 5 TEAL 6 SILVER 7 GREY 8 \
     RED 9 LIME 10 YELLOW 11 BLUE 12 FUCHSIA 13 AQUA 14 WHITE 15 \
-    MAGENTA 5 CYAN 6 PINK 218 ORANGE 214 DARK_ORANGE3 166 \
+    MAGENTA 5 CYAN 6 MALIBU 74 PINK 218 ORANGE 214 DARK_ORANGE3 166 \
   )
 
   # export color map when `__COLOR_MAP` is defined
@@ -60,50 +60,32 @@ __setup_color() { #{{{
 }
 #}}}
 
-__syslog() { #{{{
-  [[ "${_SYSLOG}" != 'yes' ]] && return
-  [[ "${DRY_RUN}" == 'yes' ]] && return
-  local TAG="${SCRIPT_NAME}"
-  local PRIORITY=user.info
-  logger -t "$TAG" -p "${PRIORITY}" "$@"
-}
-#}}}
-
-__syslog2() { #{{{
-  if [[ "${_SYSLOG}" == 'yes' ]]; then
-    [[ -n "${DRY_RUN}" ]] && return
-    [[ "$1" == '-n' ]] && shift 1
-    local TAG="${SCRIPT_NAME}"
-    local PRIORITY=user.info
-    logger -t "$TAG" -p "${PRIORITY}" "$@"
-  else
-    if [[ "$1" == '-n' ]]; then
-      shift 1
-      [[ $# -gt 0 ]] && echo -n "$@" || cat
-    else
-      [[ $# -gt 0 ]] && echo "$@" || cat
-    fi
-  fi
-}
-#}}}
-
 __show_ok() { #{{{
-  [[ "${SILENT_MODE}" ]] && return
-  echo -e "[ ${C_GREEN}OK${C_OFF} ]"
+  [[ -n "${__SILENT}" ]] && return
+  local COL
+  [[ ! "$1" =~ [0-9]+ ]] && COL="${__MSG_COL}" || COL="$1" && shift 1
+  local MSG="$1"
+
+  [[ -n "${COL}" ]] && echo -en "\\033[${COL}G"
+  echo -en " [ ${C_GREEN}OK${C_OFF}"
+  [[ -n "${MSG}" ]] && echo " ] ${MSG}" || echo " ]"
 }
 #}}}
 
 __show_failed() { #{{{
-  [ "${SILENT_MODE}" ] && return
-  [[ "$1" && "$1" -gt 0 ]] && local RES_COL="$1" || local RES_COL="${RES_COL}"
-  echo -en "\\033[${RES_COL}G"
-  echo -en "[ ${C_RED}FAILED${C_OFF}"
-  [ "$2" ] && echo " ]$2" || echo " ]"
+  [[ -n "${__SILENT}" ]] && return
+  local COL
+  [[ ! "$1" =~ [0-9]+ ]] && COL="${__MSG_COL}" || COL="$1" && shift 1
+  local MSG="$1"
+
+  [[ -n "${COL}" ]] && echo -en "\\033[${COL}G"
+  echo -en " [ ${C_RED}FAILED${C_OFF}"
+  [[ -n "${MSG}" ]] && echo " ] ${MSG}" || echo " ]"
 }
 #}}}
 
 __show_info() { #{{{
-  [[ -n "${SILENT_MODE}" ]] && return
+  [[ -n "${__SILENT}" ]] && return
   [[ "$1" == "-n" ]] && echo -en "${C_CYAN}${2}${C_OFF}" || echo -e "${C_CYAN}${1}${C_OFF}"
 }
 #}}}
@@ -153,15 +135,16 @@ _usage() { #{{{
     STATUS=1
     echo
   fi
-  echo -e "${C_CYAN}usege :${C_OFF} $SCRIPT_NAME [--silent] [-h] [-d] -c CONF_FILE"
+  local B=${C_B_MALIBU}
+  echo -e "${B}usege :${C_OFF} ${SCRIPT_NAME} [--silent] [-h] [-d] -c CONF_FILE"
   cat <<EOM
-  OPTIONS
-    --silent will not display messages (for batch job)
-    -c       specify configuration file path
-    -d       dry run
-    -h       show this help
+  ${B}OPTIONS${C_OFF}
+    ${B}--silent${C_OFF} will not display messages (for batch job)
+    ${B}-c${C_OFF}       specify configuration file path
+    ${B}-d${C_OFF}       dry run
+    ${B}-h${C_OFF}       show this help
   
-  CONFIGURATIONS
+  ${B}CONFIGURATIONS${C_OFF}
     MYSQL_ROOT_PASS=**********   # required
     BACKUP_BASE=/backup
     MYSQL=/usr/bin/mysql
@@ -187,8 +170,9 @@ _load_conf() { #{{{
   local PAT="^[ \t]*(`echo ${PARAMS[@]} | tr ' ' '|'`)="
   source <(egrep "${PAT}" "${CONF_FILE}")
 
-  __syslog "Configuration file loaded. : `readlink -f $CONF_FILE`"
-  [[ ! "${SILENT_MODE}" ]] && echo "Configuration file loaded. : `readlink -f $CONF_FILE`"
+  if [[ -z "${__SILENT}" ]]; then
+    echo "Configuration file loaded. : `readlink -f $CONF_FILE`"
+  fi
 }
 #}}}
 
@@ -199,24 +183,23 @@ _list_database() { #{{{
 }
 #}}}
 
+_script_end_cleanup() { #{{{
+  [[ -d "${_BACKUP_TMP_DIR}" ]] && rm -rf "${_BACKUP_TMP_DIR}"
+}
+#}}}
+
 #-------------------------------------------------------------------------------
 #- Main process ----------------------------------------------------------------
 #-------------------------------------------------------------------------------
-tty -s || _NO_TTY=yes
-if [[ "${_NO_TTY}" == 'yes' ]]; then
-  _SYSLOG=yes
-else
-  __setup_color
-fi
+__setup_color
 
 #- Get options -----------------------------------------------------------------
-[[ "$1" = "--silent" ]] && SILENT_MODE=yes && shift
+[[ "$1" = "--silent" ]] && __SILENT=yes && shift
 while getopts c:dh OPT; do
   case "$OPT" in
     c) CONF_FILE=$OPTARG
       ;;
-    d) DRY_RUN=yes
-      _SYSLOG=
+    d) _DRY_RUN=yes
       ;;
     h|\?) _usage
       ;;
@@ -235,32 +218,33 @@ _load_conf "${CONF_FILE}"
 if [[ ! -x "$COMPRESS_PROG" ]]; then
   __show_warn "$COMPRESS_PROG is not found. Use gzip."
   COMPRESS_PROG=""
-  TAR_OPT="z${TAR_OPT}"
+  TAR_OPT+=(-z)
   ARCHIVE_FILE_SUFFIX=.gz
 fi
-TAR_OPT="${TAR_OPT}f"
 ARCHIVE_FILE=${BACKUP_BASE}/mysql/"mysql-`LANG=C date "${DATE_FORMAT}"`.tar${ARCHIVE_FILE_SUFFIX}"
+TAR_OPT+=(-f ${ARCHIVE_FILE})
 
 #- Main process ----------------------------------------------------------------
 
-[[ "$DRY_RUN" == 'yes' ]] && __show_info "[DRY-RUN]"
+[[ "$_DRY_RUN" == 'yes' ]] && __show_info "[DRY-RUN]"
 
-__syslog "Backup start."
-__show_info "Backup start."
+__show_info "Backup start." 
 
-if [[ "${DRY_RUN}" != 'yes' ]]; then
+if [[ "${_DRY_RUN}" != 'yes' ]]; then
   DIR="`dirname $ARCHIVE_FILE`" 
   __prepare_dir "${DIR}" || __error_end "Unable to create directory. : ${DIR}"
-  BACKUP_TMP_DIR=`mktemp -d`
 fi
+_BACKUP_TMP_DIR=`mktemp -d`
 DUMP_STATUS=0
 
 
+#-----------------------------------------------------------
 # Dump each databases
+#-----------------------------------------------------------
 for DBNAME in `_list_database`; do
-  BACKUP_SQL=${BACKUP_TMP_DIR}/${DBNAME}.sql
+  BACKUP_SQL=${_BACKUP_TMP_DIR}/${DBNAME}.sql
   OPT=(-u root)
-  if [[ "${DRY_RUN}" != 'yes' ]]; then
+  if [[ "${_DRY_RUN}" != 'yes' ]]; then
     OPT+=(-p${MYSQL_ROOT_PASS})
   else
     OPT+=(-P)
@@ -273,15 +257,17 @@ for DBNAME in `_list_database`; do
   fi
   OPT+=(${DBNAME})
 
+  if [[ -z "${__SILENT}" ]]; then
+    echo -n "  Backup ${DBNAME} to ${BACKUP_SQL} ... "
+  fi
 
-  __syslog "  Backup ${DBNAME} to ${BACKUP_SQL} ... "
-  [[ ! "${SILENT_MODE}" ]] && echo -n "  Backup ${DBNAME} to ${BACKUP_SQL} ... "
-  if [[ "$DRY_RUN" == 'yes' ]]; then
+  if [[ "$_DRY_RUN" == 'yes' ]]; then
     echo
     echo -e "  [${C_YELLOW}dry-run${C_OFF}] ${MYSQLDUMP} ${OPT[@]}"
     continue
   fi
 
+  # do mysqldump
   ${MYSQLDUMP} ${OPT[@]} > ${BACKUP_SQL}
   RESULT=$?
   if [[ ${RESULT} -eq 0 ]]; then
@@ -289,47 +275,43 @@ for DBNAME in `_list_database`; do
     SIZE=`ls -l $BACKUP_SQL | awk '{print $5}'`
     if [[ $SIZE -ge 0 ]]; then
       __show_ok
-      __syslog "  Dump $DBNAME successful."
     else
       __show_failed
-      __syslog "  Dump $DBNAME failed."
       DUMP_STATUS=1
     fi
    else
      __show_failed
-     __syslog "  Dump $DBNAME failed."
      DUMP_STATUS=1
    fi
 done
 
+#-----------------------------------------------------------
+# Archive
+#-----------------------------------------------------------
+
+TAR_OPT+=(--use-compress-prog=${COMPRESS_PROG} *.sql)
 # When dry-run mode exit here
-if [[ "$DRY_RUN" ]]; then
+if [[ "$_DRY_RUN" ]]; then
   __show_info -n "[DRY-RUN]"
-  echo " Will be archived : tar ${TAR_OPT} ${ARCHIVE_FILE} --use-compress-prog=${COMPRESS_PROG} *.sql"
+  echo " Will be archived : tar ${TAR_OPT[@]}"
   exit 0
 fi
 
 if [[ "${DUMP_STATUS}" -eq 1 ]]; then
-  rm -rf $BACKUP_TMP_DIR
   __error_end "Failed to dump databases."
 fi
 
 # Archive
-pushd $BACKUP_TMP_DIR > /dev/null
-__syslog "  Archiving... : $ARCHIVE_FILE"
-[[ ! ${SILENT_MODE} ]] && echo "  Archiving... : $ARCHIVE_FILE"
-tar ${TAR_OPT} ${ARCHIVE_FILE} --use-compress-prog=${COMPRESS_PROG} *.sql
+pushd ${_BACKUP_TMP_DIR} > /dev/null
+[[ -z "${__SILENT}" ]] && echo "  Archiving... : $ARCHIVE_FILE"
+tar ${TAR_OPT[@]}
 popd > /dev/null
-
-rm -rf $BACKUP_TMP_DIR
 
 if [[ -e $ARCHIVE_FILE ]]; then
   __show_info "Backup was successfully completed. : ${ARCHIVE_FILE}"
-  __syslog "Backup was successfully completed. : ${ARCHIVE_FILE}"
   exit 0
 else
   __show_error "Backup failed. : ${ARCHIVE_FILE}"
-  __syslog "Backup failed. : ${ARCHIVE_FILE}"
   exit 1
 fi
 
