WIP

diff --git a/mysql-backup b/mysql-backup
--- a/mysql-backup
+++ b/mysql-backup
@@ -13,85 +13,76 @@ SCRIPT_NAME=`basename $0`
 # User Configuration -----------------------------------------------------------
 MYSQL_ROOT_PASS=
 BACKUP_BASE=/backup
+MYSQL=/usr/bin/mysql
 MYSQLDUMP=/usr/bin/mysqldump
-MYSQLSHOW=/usr/bin/mysqlshow
 COMPRESS_PROG=/usr/bin/pigz
 ARCHIVE_FILE_SUFFIX=.gz
 DATE_FORMAT=+%Y%m%d
 #-------------------------------------------------------------------------------
 
-DUMP_OPT="--lock-all-tables --hex-blob --add-drop-database --add-drop-table"
+DUMP_OPT=(--lock-all-tables --hex-blob --add-drop-database --add-drop-table)
 DUMP_OPT_INFORMATION_SCHEMA=""
-DUMP_OPT_MYSQL="--lock-all-tables --events"
+DUMP_OPT_MYSQL=(--lock-all-tables --events)
 TAR_OPT=c
+
+_SYSLOG=
 
 #-------------------------------------------------------------------------------
 #- common functions ------------------------------------------------------------
 
 __setupcolor() { #{{{
-  # Escape sequence
-  ESC="\e["
-  ESCEND=m
-  C_OFF=${ESC}${ESCEND}
+  local I
+  local COLOR_MAP=(\
+    BLACK 0 MAROON 1 GREEN 2 OLIVE 3 NAVY 4 PURPLE 5 TEAL 6 SILVER 7 GREY 8 \
+    RED 9 LIME 10 YELLOW 11 BLUE 12 FUCHSIA 13 AQUA 14 WHITE 15 \
+    MAGENTA 5 CYAN 6 PINK 218 ORANGE 214 DARK_ORANGE3 166 \
+  )
 
-  # normal
-  C_BLACK="${ESC}30${ESCEND}"
-  C_RED="${ESC}31${ESCEND}"
-  C_GREEN="${ESC}32${ESCEND}"
-  C_YELLOW="${ESC}33${ESCEND}"
-  C_BLUE="${ESC}34${ESCEND}"
-  C_MAGENTA="${ESC}35${ESCEND}"
-  C_CYAN="${ESC}36${ESCEND}"
-  C_WHITE="${ESC}37${ESCEND}"
+  C_OFF=`tput sgr0`   # Reset attribute
+  C_BOLD=`tput bold`  # Bold mode
+  C_REV=`tput rev`    # Reverse mode
+  C_UL=`tput smul`    # Underline mode
 
-  RES_COL=72
-  MOVE_TO_COL="echo -en \\033[${RES_COL}G"
+  for ((I=0; I<${#COLOR_MAP[@]}; I+=2)); do
+    # echo "$I : ${COLOR_MAP[$I]} ${COLOR_MAP[(($I + 1))]}"
+    eval "C_${COLOR_MAP[$I]}=\`tput setaf ${COLOR_MAP[(($I + 1))]}\`"
+    eval "C_B_${COLOR_MAP[$I]}=\`tput bold\`\`tput setaf ${COLOR_MAP[(($I + 1))]}\`"
+    eval "C_U_${COLOR_MAP[$I]}=\`tput smul\`\`tput setaf ${COLOR_MAP[(($I + 1))]}\`"
+    eval "C_R_${COLOR_MAP[$I]}=\`tput bold\`\`tput rev\`\`tput setaf ${COLOR_MAP[(($I + 1))]}\`"
+  done
 }
 #}}}
 
 __syslog() { #{{{
-  # syslog へログを出力します。
-  #  引数を指定しない場合は、標準入力からの読み取り結果をログ出力します。
-  #
-  # 【環境変数】LOG_TAG            タグ
-  #             LOG_FACILITY(任意) ファシリティ(省略時はuser)
-  #             SCRIPT_NAME (任意) スクリプト名
-  # 【引数】 $1:ログメッセージ
-  #          $2:ログレベル(省略可, 省略時は info)
+  [[ "${_SYSLOG}" != 'yes' ]] && return
+  [[ "${DRY_RUN}" == 'yes' ]] && return
+  local TAG="${SCRIPT_NAME}"
+  local PRIORITY=user.info
+  logger -t "$TAG" -p "${PRIORITY}" "$@"
+}
+#}}}
 
-  [[ -n "${DRY_RUN}" ]] && return 
-  [ ! "$SCRIPT_NAME" ] && local SCRIPT_NAME=`basename $0`
-  if [ "$LOG_TAG" ]; then
-    local TAG="${LOG_TAG}/${SCRIPT_NAME}"
-  else
+__syslog2() { #{{{
+  if [[ "${_SYSLOG}" == 'yes' ]]; then
+    [[ -n "${DRY_RUN}" ]] && return
+    [[ "$1" == '-n' ]] && shift 1
     local TAG="${SCRIPT_NAME}"
-  fi
-
-  local FACILITY=user
-  [[ "$LOG_FACILITY" ]] && FACILITY=$LOG_FACILITY
-
-  local LOG_LEVEL=info
-  [[ "$2" ]] && LOG_LEVEL="$2"
-
-  if [[ "$1" ]]; then
-    logger -t "$TAG" -p "${FACILITY}.${LOG_LEVEL}" "$1"
+    local PRIORITY=user.info
+    logger -t "$TAG" -p "${PRIORITY}" "$@"
   else
-    local OLDIFS="$IFS"
-    IFS=
-    while read LOG_LINE; do
-      logger -t "$TAG" -p "${FACILITY}.${LOG_LEVEL}" "$LOG_LINE"
-    done
-    IFS="$OLDIFS"
+    if [[ "$1" == '-n' ]]; then
+      shift 1
+      [[ $# -gt 0 ]] && echo -n "$@" || cat
+    else
+      [[ $# -gt 0 ]] && echo "$@" || cat
+    fi
   fi
 }
 #}}}
 
 __show_ok() { #{{{
-  [ "${SILENT_MODE}" ] && return
-  [[ "$1" && "$1" -gt 0 ]] && local RES_COL="$1" || local RES_COL="${RES_COL}"
-  echo -en "\\033[${RES_COL}G"
-  echo -en "[ ${C_GREEN}OK${C_OFF}"
-  [ "$2" ] && echo " ]$2" || echo " ]"
+  [[ "${SILENT_MODE}" ]] && return
+  echo -e "[ ${C_GREEN}OK${C_OFF} ]"
 }
 #}}}
 
@@ -116,13 +107,20 @@ __show_warn() { #{{{
 #}}}
 
 __show_error() { #{{{
-  echo -e "[${C_RED}ERROR${C_OFF}] $1"
+  echo -e "[${C_RED}ERROR${C_OFF}] $@" >&2
+  __syslog "[ERROR] $@"
 }
 #}}}
 
 __error_end() { #{{{
   __show_error "$1"; exit 1
 }
+#}}}
+
+__script_end() { #{{{
+  [[ -d ${BACKUP_TMP_DIR} ]] && rm -rf ${BACKUP_TMP_DIR}
+}
+trap '__script_end' EXIT
 #}}}
 
 __prepare_dir() { #{{{
@@ -136,14 +134,16 @@ __prepare_dir() { #{{{
 }
 #}}}
 
-
 #-------------------------------------------------------------------------------
 #- functions -------------------------------------------------------------------
 
-# usage
-#{{{
-_usage() {
-  [ "$1" ] && __show_error "$1"
+_usage() { #{{{
+  local STATUS=0
+  if [[ -n "$@" ]]; then
+    __show_error "$@"
+    STATUS=1
+    echo
+  fi
   echo -e "${C_CYAN}usege :${C_OFF} $SCRIPT_NAME [--silent] [-h] [-d] -c CONF_FILE"
   cat <<EOM
   OPTIONS
@@ -155,20 +155,50 @@ _usage() {
   CONFIGURATIONS
     MYSQL_ROOT_PASS=**********   # required
     BACKUP_BASE=/backup
+    MYSQL=/usr/bin/mysql
     MYSQLDUMP=/usr/bin/mysqldump
-    MYSQLSHOW=/usr/bin/mysqlshow
     COMPRESS_PROG=/usr/bin/pigz
     ARCHIVE_FILE_SUFFIX=.gz
     DATE_FORMAT=+%Y%m%d
 EOM
-  exit 1
+  exit $STATUS
+}
+#}}}
+
+_load_conf() { #{{{
+  local CONF_FILE="$1"
+  [[ -z "$CONF_FILE" ]] && __error_end "Configuration file is not specified."
+  if [[ ! -f "${CONF_FILE}" ]]; then
+    __error_end "Configuration file is not found. : ${CONF_FILE}"
+  fi
+
+  local PARAMS=(MYSQL_ROOT_PASS BACKUP_BASE MYSQL MYSQLDUMP)
+  PARAMS+=(COMPRESS_PROG ARCHIVE_FILE_SUFFIX DATE_FORMAT)
+
+  local PAT="^[ \t]*(`echo ${PARAMS[@]} | tr ' ' '|'`)="
+  source <(egrep "${PAT}" "${CONF_FILE}")
+
+  __syslog "Configuration file loaded. : `readlink -f $CONF_FILE`"
+  [[ ! "${SILENT_MODE}" ]] && echo "Configuration file loaded. : `readlink -f $CONF_FILE`"
+}
+#}}}
+
+_list_database() { #{{{
+  ${MYSQL} -uroot -p${MYSQL_ROOT_PASS} <<<"show databases;" -N \
+    | egrep -v '^(information_schema|performance_schema)$' \
+    | xargs
 }
 #}}}
 
 #-------------------------------------------------------------------------------
 #- Main process ----------------------------------------------------------------
 #-------------------------------------------------------------------------------
-[[ ! "$NO_COLOR" ]] && __setupcolor
+tty -s || _NO_TTY=yes
+if [[ "${_NO_TTY}" == 'yes' ]]; then
+  _SYSLOG=yes
+else
+  __setupcolor
+fi
 
 #- Get options -----------------------------------------------------------------
 [[ "$1" = "--silent" ]] && SILENT_MODE=yes && shift
@@ -177,6 +207,7 @@ while getopts c:dh OPT; do
     c) CONF_FILE=$OPTARG
       ;;
     d) DRY_RUN=yes
+      _SYSLOG=
       ;;
     h|\?) _usage
       ;;
@@ -185,20 +216,13 @@ done
 shift `expr $OPTIND - 1`
 
 #- Load configuration file -----------------------------------------------------
-[[ ! "$CONF_FILE" ]] && __error_end "Configuration file path is not specified."
-if [[ -f "$CONF_FILE" ]]; then
-  . "${CONF_FILE}"
-  __syslog "Configuration file loaded. : `readlink -f $CONF_FILE`"
-else
-  __error_end "File not found. : $CONF_FILE"
-fi
+_load_conf "${CONF_FILE}"
 
 #- Check options ---------------------------------------------------------------
-if [[ ! "$MYSQL_ROOT_PASS" ]]; then
-  echo -e "${C_RED}An environmental valiable MYSQL_ROOT_PASS is not set.${C_OFF}"
-  echo ''
-  _usage
-fi
+[[ ! "$MYSQL_ROOT_PASS" ]] && _usage "An environmental valiable MYSQL_ROOT_PASS is not set."
+[[ -z "${MYSQL}" ]] && MYSQL=`which mysql 2> /dev/null`
+[[ ! -x "${MYSQL}" ]] && __error_end "Unable to find mysql executable. : ${MYSQL}"
+
 if [[ ! -x "$COMPRESS_PROG" ]]; then
   __show_warn "$COMPRESS_PROG is not found. Use gzip."
   COMPRESS_PROG=""
@@ -206,48 +230,66 @@ if [[ ! -x "$COMPRESS_PROG" ]]; then
   ARCHIVE_FILE_SUFFIX=.gz
 fi
 TAR_OPT="${TAR_OPT}f"
-ARCHIVE_FILE=$BACKUP_BASE/mysql/"mysql-`date "$DATE_FORMAT"`.tar${ARCHIVE_FILE_SUFFIX}"
+ARCHIVE_FILE=${BACKUP_BASE}/mysql/"mysql-`LANG=C date "${DATE_FORMAT}"`.tar${ARCHIVE_FILE_SUFFIX}"
 
 #- Main process ----------------------------------------------------------------
-[[ "$DRY_RUN" ]] && __show_info "[DRY-RUN]"
+
+[[ "$DRY_RUN" == 'yes' ]] && __show_info "[DRY-RUN]"
 
 __syslog "Backup start."
 __show_info "Backup start."
 
-__prepare_dir `dirname $ARCHIVE_FILE` || __error_end "Unable to create directory"
-
+if [[ "${DRY_RUN}" != 'yes' ]]; then
+  DIR="`dirname $ARCHIVE_FILE`" 
+  __prepare_dir "${DIR}" || __error_end "Unable to create directory. : ${DIR}"
+  BACKUP_TMP_DIR=`mktemp -d`
+fi
 DUMP_STATUS=0
 
-[[ ! "$DRY_RUN" ]] && BACKUP_TMP_DIR=`mktemp -d`
 
 # Dump each databases
-for DBNAME in `${MYSQLSHOW} -u root -p${MYSQL_ROOT_PASS} | tail -n +4 | sed -e '$d' | awk '{print $2}'`; do
-   BACKUP_SQL=${BACKUP_TMP_DIR}/${DBNAME}.sql
-   OPT=$DUMP_OPT
+for DBNAME in `_list_database`; do
+  BACKUP_SQL=${BACKUP_TMP_DIR}/${DBNAME}.sql
+  OPT=(-u root)
+  if [[ "${DRY_RUN}" != 'yes' ]]; then
+    OPT+=(-p${MYSQL_ROOT_PASS})
+  else
+    OPT+=(-P)
+  fi
 
-   [ "$DBNAME" == "mysql" ] && OPT=$DUMP_OPT_MYSQL
+  if [[ "$DBNAME" == "mysql" ]]; then
+    OPT+=(${DUMP_OPT_MYSQL[@]})
+  else
+    OPT+=(${DUMP_OPT[@]})
+  fi
+  OPT+=(${DBNAME})
 
-   echo -n "  Backup $DBNAME to $BACKUP_SQL ..."
-   if [[ ! "$DRY_RUN" ]]; then
-     ${MYSQLDUMP} -u root -p${MYSQL_ROOT_PASS} ${OPT} ${DBNAME} > ${BACKUP_SQL}
-     if [ $? ]; then
-       # check file size
-       SIZE=`ls -l $BACKUP_SQL | awk '{print $5}'`
-       if [ $SIZE -ge 0 ]; then
-         __syslog "  Dump $DBNAME successful."
-         __show_ok
-       else
-         __show_failed
-         __syslog "  Dump $DBNAME failed."
-         DUMP_STATUS=1
-       fi
-     else
-       __show_failed
-       __syslog "  Dump $DBNAME failed."
-       DUMP_STATUS=1
-     fi
+
+  __syslog "  Backup ${DBNAME} to ${BACKUP_SQL} ... "
+  [[ ! "${SILENT_MODE}" ]] && echo -n "  Backup ${DBNAME} to ${BACKUP_SQL} ... "
+  if [[ "$DRY_RUN" == 'yes' ]]; then
+    echo
+    echo -e "  [${C_YELLOW}dry-run${C_OFF}] ${MYSQLDUMP} ${OPT[@]}"
+    continue
+  fi
+
+  ${MYSQLDUMP} ${OPT[@]} > ${BACKUP_SQL}
+  RESULT=$?
+  if [[ ${RESULT} -eq 0 ]]; then
+    # check file size
+    SIZE=`ls -l $BACKUP_SQL | awk '{print $5}'`
+    if [[ $SIZE -ge 0 ]]; then
+      __show_ok
+      __syslog "  Dump $DBNAME successful."
+    else
+      __show_failed
+      __syslog "  Dump $DBNAME failed."
+      DUMP_STATUS=1
+    fi
    else
-     echo ""
+     __show_failed
+     __syslog "  Dump $DBNAME failed."
+     DUMP_STATUS=1
    fi
 done
 
@@ -258,7 +300,7 @@ if [[ "$DRY_RUN" ]]; then
   exit 0
 fi
 
-if [[ $DUMP_STATUS -eq 1 ]]; then
+if [[ "${DUMP_STATUS}" -eq 1 ]]; then
   rm -rf $BACKUP_TMP_DIR
   __error_end "Failed to dump databases."
 fi
@@ -266,19 +308,19 @@ fi
 # Archive
 pushd $BACKUP_TMP_DIR > /dev/null
 __syslog "  Archiving... : $ARCHIVE_FILE"
-echo "  Archiving... : $ARCHIVE_FILE"
+[[ ! ${SILENT_MODE} ]] && echo "  Archiving... : $ARCHIVE_FILE"
 tar ${TAR_OPT} ${ARCHIVE_FILE} --use-compress-prog=${COMPRESS_PROG} *.sql
 popd > /dev/null
 
 rm -rf $BACKUP_TMP_DIR
 
 if [[ -e $ARCHIVE_FILE ]]; then
-  __show_info "Backup was successfully completed. :${ARCHIVE_FILE}"
-  __syslog "Backup was successfully completed. :${ARCHIVE_FILE}"
+  __show_info "Backup was successfully completed. : ${ARCHIVE_FILE}"
+  __syslog "Backup was successfully completed. : ${ARCHIVE_FILE}"
   exit 0
 else
-  __show_error "Backup failed. :${ARCHIVE_FILE}"
-  __syslog "Backup failed. :${ARCHIVE_FILE}"
+  __show_error "Backup failed. : ${ARCHIVE_FILE}"
+  __syslog "Backup failed. : ${ARCHIVE_FILE}"
   exit 1
 fi
 
