Enable backup file rotation

diff --git a/mysql-backup b/mysql-backup
--- a/mysql-backup
+++ b/mysql-backup
@@ -15,6 +15,7 @@ COMPRESS_PROG=/usr/bin/pigz
 ARCHIVE_FILE_PREFIX=mysql-
 ARCHIVE_FILE_SUFFIX=.gz
 DATE_FORMAT=+%Y%m%d-%H%M%S
+RETENTION=
 MYSQL_USER=root
 MYSQL_PASSWORD=
 CONTAINER_NAME=
@@ -138,6 +139,65 @@ __make_temp_simple() { #{{{
 }
 #}}}
 
+__rotate_files() { #{{{
+  local RETENTION="$1"
+  local PATTERN="$2"
+  local RESULT=0
+  local F CNT
+
+  ___do_rotate() {
+    local F="$1"
+    local MSG
+    if [[ ${__DRY_RUN} != 'yes' ]]; then
+      echo -n "  Deleting... $F"
+      MSG=`rm "$F" 2>&1`
+      if [[ $? -eq 0 ]]; then
+        __show_ok
+        return 0
+      else
+        echo -e "\n  [${C_RED}FAILED${C_OFF}] ${MSG}"
+        return 1
+      fi
+    else
+      echo "  will be deleted : $F"
+    fi
+  }
+
+  if [[ ! "${RETENTION}" =~ [0-9]+ ]]; then
+    __show_error "Invalid retention : ${RETENTION}"
+    return 1
+  fi
+
+  if [[ ! "$PATTERN" =~ ^(.+)/([^/]+)$ ]]; then
+    __show_error "Invalid pattern : ${PATTERN}"
+    return 1
+  fi
+  local BASEDIR="${BASH_REMATCH[1]}"
+  local FILE_PATTERN="${BASH_REMATCH[2]}"
+
+  local FIND_ARGS=("${BASEDIR}" -mindepth 1 -maxdepth 1 -type f -name "${FILE_PATTERN}")
+  echo ">>> ${FIND_ARGS[@]}"
+
+  # delete empty files
+  __show_info "Deleting empty files..."
+  CNT=0
+  while read F; do
+    ___do_rotate "$F" && CNT=$(( $CNT + 1 )) || RESULT=1
+  done < <(find ${FIND_ARGS[@]} -size 0c)
+  [[ "$CNT" -eq 0 ]] && echo "  nothing to delete."
+
+  # delete old files
+  __show_info "Deleting old files..."
+  CNT=0
+  while read F; do
+    ___do_rotate "$F" && CNT=$(( $CNT + 1 )) || RESULT=1
+  done < <(find ${FIND_ARGS[@]} -size +1c | sort -n | head --lines=-${RETENTION})
+  [[ "$CNT" -eq 0 ]] && echo "  nothing to delete."
+
+  return $RESULT
+}
+#}}}
+
 #-------------------------------------------------------------------------------
 #- functions -------------------------------------------------------------------
 
@@ -171,6 +231,8 @@ _usage() { #{{{
     ARCHIVE_FILE_SUFFIX=.gz
     # Follow the specification of the date command
     DATE_FORMAT=+%Y%m%d
+    # (Optional) If not specified, no rotation will be performed  
+    RETENTION=5
 
   If MYSQL_PASSWORD is not specified, it will be read from the standard input.
 
@@ -185,6 +247,7 @@ _usage() { #{{{
     ARCHIVE_FILE_PREFIX=${ARCHIVE_FILE_PREFIX}
     ARCHIVE_FILE_SUFFIX=${ARCHIVE_FILE_SUFFIX}
     DATE_FORMAT=${DATE_FORMAT}
+    RETENTION=${RETENTION}
 EOM
   exit $STATUS
 }
@@ -198,7 +261,7 @@ _load_conf() { #{{{
   fi
 
   local PARAMS=(MYSQL_USER MYSQL_PASSWORD BACKUP_BASE MYSQL MYSQLDUMP)
-  PARAMS+=(COMPRESS_PROG ARCHIVE_FILE_PREFIX ARCHIVE_FILE_SUFFIX DATE_FORMAT)
+  PARAMS+=(COMPRESS_PROG ARCHIVE_FILE_PREFIX ARCHIVE_FILE_SUFFIX DATE_FORMAT RETENTION)
   PARAMS+=(CONTAINER_NAME)
 
   local PAT="^[ \t]*(`echo ${PARAMS[@]} | tr ' ' '|'`)="
@@ -290,7 +353,7 @@ while getopts c:fdh OPT; do
       ;;
     f) FORCE_OVERWRITE=yes
       ;;
-    d) _DRY_RUN=yes
+    d) __DRY_RUN=yes
       ;;
     h|\?) _usage
       ;;
@@ -345,16 +408,17 @@ if [[ ! -x "$COMPRESS_PROG" ]]; then
   ARCHIVE_FILE_SUFFIX=.gz
 fi
 ARCHIVE_FILE=${BACKUP_BASE}/"${ARCHIVE_FILE_PREFIX}`LANG=C date "${DATE_FORMAT}"`.tar${ARCHIVE_FILE_SUFFIX}"
+ROTATE_PATTERN=${BACKUP_BASE}/${ARCHIVE_FILE_PREFIX}*.tar${ARCHIVE_FILE_SUFFIX}
 TAR_OPT+=(-f ${ARCHIVE_FILE})
 #}}}
 
 #- Main process ----------------------------------------------------------------
 
-[[ "$_DRY_RUN" == 'yes' ]] && echo -e "${C_YELLOW}[DRY-RUN]${C_OFF}"
+[[ "$__DRY_RUN" == 'yes' ]] && echo -e "${C_YELLOW}[DRY-RUN]${C_OFF}"
 
 __show_info "Backup start." 
 
-if [[ "${_DRY_RUN}" != 'yes' ]]; then
+if [[ "${__DRY_RUN}" != 'yes' ]]; then
   DIR="`dirname $ARCHIVE_FILE`" 
   __prepare_dir "${DIR}" || __error_end "Unable to create directory. : ${DIR}"
 fi
@@ -385,7 +449,7 @@ for DBNAME in `_list_database`; do
     echo -n "  Backup ${DBNAME} to ${DBNAME}.sql ... "
   fi
 
-  if [[ "$_DRY_RUN" == 'yes' ]]; then
+  if [[ "$__DRY_RUN" == 'yes' ]]; then
     echo
     echo -e "  ${C_YELLOW}[dry-run]${C_OFF} ${MYSQLDUMP} ${OPT[@]}"
     continue
@@ -415,7 +479,7 @@ done
 
 TAR_OPT+=(--use-compress-prog=${COMPRESS_PROG} *.sql)
 # When dry-run mode exit here
-if [[ "$_DRY_RUN" ]]; then
+if [[ "$__DRY_RUN" ]]; then
   echo -n "${C_YELLOW}[DRY-RUN]${C_OFF}"
   echo " Will be archived : tar ${TAR_OPT[@]}"
   exit 0
@@ -433,10 +497,14 @@ popd > /dev/null
 
 if [[ -e $ARCHIVE_FILE ]]; then
   __show_info "Backup was successfully completed. : ${ARCHIVE_FILE}"
-  exit 0
 else
   __show_error "Backup failed. : ${ARCHIVE_FILE}"
   exit 1
+fi
+
+# Rotate old files
+if [[ -n "${RETENTION}" ]]; then
+  __rotate_files ${RETENTION} "${ROTATE_PATTERN}"
 fi
 
 # vim: ts=2 sw=2 sts=2 et nu foldmethod=marker
